import { Request, Response } from "express";
export const uploadImage = async (req: Request, res: Response) => {
  try {
    if (!req.file) {
      return res.status(400).json({ message: "No file provided." });
    }

    // File URL is generated by Cloudinary via multer
    res.status(200).json({ imageUrl: req.file.path });
  } catch (error) {
    res.status(500).json({ message: "Image upload failed.", error });
  }
};
